### ISSUE TITLE
feature(i128_type) may not be used on the stable release channel 

### ISSUE THREAD

**Issue by mathiasrw** [itchyny/pihex#1]
When I compile I get

```
error[E0554]: #![feature] may not be used on the stable release channel         
 --> /Users/mrw/.cargo/registry/src/github.com-1ecc6299db9ec823/pihex-0.1.1/src/lib.rs:1:1
  |                                                                             
1 | #![feature(i128_type)]                                                      
  | ^^^^^^^^^^^^^^^^^^^^^^                                                      
                                                                                
error: aborting due to previous error                                           
                                                                                
For more information about this error, try `rustc --explain E0554`. 
```

I imagine this is due to changes in the rust compiler since the code was written. 

Any inputs that can help me sort this out? (not really strong in Rust)

**Comment by itchyny** [comment]
I don't check the behavior but installing nightly build of Rust might help.

**Comment by itchyny** [comment]
For reference, I can confirm the test passes with nightly, see https://travis-ci.org/itchyny/pihex-rs/builds/213383639. Two years pass since I wrote the command but unfortunately the i128 feature seems to be still unstable.

**Comment by itchyny** [comment]
@mathiasrw sorry, i128 is already available in stable release. I removed the feature flag and pushed repo so it should be compiled with Rust stable.
